# Generated by Django 5.0.7 on 2024-09-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0004_alter_photo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanksDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview', models.CharField(blank=True, max_length=100, null=True)),
                ('diary', models.TextField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, null=True, to='medias.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.CharField(max_length=100, null=True)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.thanksdate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
