# Generated by Django 5.0.7 on 2024-09-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thank',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thanks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thanksdate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thanksdates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thank',
            name='Date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks', to='thanks.thanksdate'),
        ),
    ]
