# Generated by Django 5.0.7 on 2024-09-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_thank_user_thanksdate_user_alter_thank_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thank',
            old_name='Date',
            new_name='when',
        ),
        migrations.RemoveField(
            model_name='thanksdate',
            name='photos',
        ),
    ]
