# Generated by Django 5.0.7 on 2024-09-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0003_rename_date_thank_when_remove_thanksdate_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thank',
            old_name='when',
            new_name='thanksDates',
        ),
    ]
