# Generated by Django 5.0.7 on 2024-09-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0004_rename_when_thank_thanksdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thank',
            old_name='thanksDates',
            new_name='thanksDate',
        ),
    ]
