# Generated by Django 5.0.7 on 2024-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('item', 'Item'), ('chat', 'Chat')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
