# Generated by Django 5.0.7 on 2024-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_tag_item_category_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
