# Generated by Django 5.0.7 on 2024-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_remove_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="comment",
        ),
        migrations.AlterField(
            model_name="tag",
            name="tags",
            field=models.CharField(
                choices=[("game", "Game"), ("util", "Util"), ("healing", "Healing")],
                max_length=30,
                null=True,
            ),
        ),
    ]
