# Generated by Django 5.0.7 on 2024-08-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_comment_alter_tag_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
