# Generated by Django 5.0.7 on 2024-08-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
