# Generated by Django 5.0.7 on 2024-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(blank=True, choices=[('c', 'C'), ('cpp', 'CPP'), ('python', 'Python'), ('javascript', 'Javascript'), ('dart', 'Dart'), ('java', 'Java'), ('etc', 'Etc')], max_length=20, null=True),
        ),
    ]
