# Generated by Django 5.0.7 on 2024-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='tips_highlight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tips_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
