# Generated by Django 5.0.7 on 2024-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_is_liked_item_tips_highlight_item_tips_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rules_highlight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rules_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
