# Generated by Django 5.0.7 on 2024-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_rules_highlight_item_rules_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_liked',
            field=models.BooleanField(),
        ),
    ]
