# Generated by Django 5.0.7 on 2024-10-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_item_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
