# Generated by Django 5.0.7 on 2024-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_video_description_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(),
        ),
    ]
