# Generated by Django 5.0.7 on 2024-09-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
