# Generated by Django 5.0.7 on 2024-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_file_delete_rating'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item',
            field=models.ManyToManyField(to='items.item'),
        ),
    ]
