# Generated by Django 5.0.7 on 2024-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_tags'),
        ('wishlists', '0002_alter_wishlist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item',
            field=models.ManyToManyField(related_name='wishlists', to='items.item'),
        ),
    ]
