# Generated by Django 5.0.7 on 2024-08-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_alter_wishlist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='items',
        ),
    ]
