# Generated by Django 5.0.7 on 2024-08-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_tags'),
        ('wishlists', '0004_rename_item_wishlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='items.item'),
        ),
    ]
