# Generated by Django 5.0.7 on 2024-08-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='chats.chat'),
        ),
    ]
