# Generated by Django 5.0.7 on 2024-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatroom_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
