# Generated by Django 5.0.7 on 2024-08-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chatroom_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user',
            new_name='users',
        ),
    ]
