# Generated by Django 5.0.7 on 2024-08-25 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_rename_user_chatroom_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(null=True, related_name='chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
